[project]
name = "music-lab"
version = "0.1.0"
description = "Reproductor musical inmersivo con FastAPI"
requires-python = ">=3.14"
dependencies = [
    "annotated-doc==0.0.4",
    "annotated-types==0.7.0",
    "antlr4-python3-runtime==4.9.3",
    "anyio==4.14.1",
    "auditok==0.4.2",
    "certifi==2026.6.17",
    "charset-normalizer==3.4.9",
    "click==8.4.2",
    "cloudpickle==3.1.2",
    "cython==3.2.8",
    "decorator==5.3.1",
    "demucs==4.0.1",
    "dora-search==0.1.12",
    "dtw-python==1.7.5",
    "einops==0.8.2",
    "fastapi==0.136.1",
    "filelock==3.29.7",
    "fsspec==2026.6.0",
    "h11==0.16.0",
    "idna==3.18",
    "imageio==2.37.3",
    "imageio-ffmpeg==0.6.0",
    "jinja2==3.1.6",
    "julius==0.2.8",
    "lameenc==1.8.4",
    "llvmlite==0.48.0",
    "markdown-it-py==4.2.0",
    "markupsafe==3.0.3",
    "mdurl==0.1.2",
    "more-itertools==11.1.0",
    "moviepy==2.2.1",
    "mpmath==1.3.0",
    "networkx==3.6.1",
    "numba==0.66.0",
    "numpy==2.4.6",
    "omegaconf==2.3.1",
    "openai-whisper==20250625",
    "openunmix==1.3.0",
    "pillow==11.3.0",
    "proglog==0.1.12",
    "pydantic==2.13.4",
    "pydantic-core==2.46.4",
    "pyfiglet==1.0.4",
    "pygments==2.20.0",
    "python-dotenv==1.2.2",
    "pyyaml==6.0.3",
    "regex==2026.6.28",
    "requests==2.34.2",
    "retrying==1.4.2",
    "rich==15.0.0",
    "scipy==1.18.0",
    "setuptools==81.0.0",
    "starlette==1.3.1",
    "submitit==1.5.4",
    "sympy==1.14.0",
    "tiktoken==0.13.0",
    "torch==2.12.1",
    "torchaudio==2.11.0",
    "torchcodec==0.14.0",
    "tqdm==4.68.4",
    "treetable==0.2.6",
    "typing-extensions==4.16.0",
    "typing-inspection==0.4.2",
    "urllib3==2.7.0",
    "uvicorn==0.38.0",
    "whisper-timestamped==1.15.9",
    "yt-dlp==2026.7.4",
]
